name: Deploy Carbon Handbook

on:
  push:
    branches: [main] 

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      
      - name: Install deps
        run: npm install

      - name: Build VuePress
        run: npm run docs:build

      - name: Deploy 
        uses: peaceiris/actions-gh-pages@v3
        with:
          build_dir: ./docs/.vuepress/dist
          publish_dir: ./docs/.vuepress/dist
          github_token: ${{ secrets.PAT }}
      
        
