name: Deploy Carbon Handbook

on:
  push:
    branches: [main] 

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # или 18

      - name: Install dependencies
        run: npm install

      - name: Build VuePress
        run: npm run docs:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT }}
          publish_dir: /docs/.vuepress/dist  # путь к билду
          keep_files: false
